### PR TITLE
Fixed russian translations

### PR DESCRIPTION
**Pull request by GrigLog**
Right now russian translations are simply made by a Google Translator. Or a human with  a very poor knowledge of russian language. They contain so many mistakes that its almost impossible to read. Thats why Ive fixed them.

### CODE REVIEW

**Comment by xniki119x** [comment]
Как тот, кто говорит на русском полностью согласен что перевод - отстой. Также прошу его исправить.

**Comment by Darkhax** [comment]
Thanks for reaching out and trying to improve the translations. The original contributor was @DrHesperus who lives in Russia and has been a well respected Russian translator for our community. If there are mistakes I am more than willing to approve them however I don't speak Russian and have no way to verify these claims.

**Comment by Darkhax** [comment]
I've had a few others in the community verify that the original translations are low quality. Apparently the reputation of DrHesperus has also been called into question by other authors. Thank you for bringing this to my attention.

**Comment by Annijang** [comment]
> 现在俄语翻译只是由谷歌翻译器完成。或者是一个对俄语知之甚少的人。它们包含如此多的错误，几乎无法阅读。这就是我修复它们的原因。
I translated a Russian mod called "Soviet era mod". As a Chinese player, I don't know Russian at all. It's impossible to change Russian to Chinese without software.

**Pull request merged**
