### PR TITLE
Update uk_ua.json

### PR DESCRIPTION
**Pull request by Altegar**

### CODE REVIEW

**Comment by Darkhax** [comment]
Thanks for the help.

**Comment by perdakovich** [comment]
interesting translation of joke.creeper, though.

It literally says that Russian television turns people (creepers) into "zombies" (brainwashes them).
just thought I'd point it out. I myself am neutral in this, uhmm, political situation.

**Comment by Darkhax** [comment]
@goosegit11 I wasn't aware of that when I merged the PR however I think it's fine and will be keeping it. I am sorry if it offends any Russian players, but I am firmly in support of Ukraine.

**Comment by perdakovich** [comment]
@Darkhax got it. it's probably really fun for ukrainian players, and russians probably won't play with the ukrainian language, so, uhm, okay :thinking: 

btw glory to panslavism!

**Pull request merged**
